### ISSUE TITLE
Lambda Code is not bundled with package

### ISSUE THREAD

**Issue by djenniex-gg** [udondan/cdk-ec2-key-pair#299]
Trying to upgrade to the newest version, I get the following error

```
Error: Cannot find asset at /Users/someone/code/node_modules/cdk-ec2-key-pair/lambda/code.zip
    at new AssetStaging (/Users/someone/code/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2119)
    at new Asset (/Users/someone/code/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1080)
    at AssetCode.bind (/Users/someone/code/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:4881)
    at new Function (/Users/someone/code/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:9422)
    at KeyPair.ensureLambda (/Users/someone/code/node_modules/cdk-ec2-key-pair/lib/index.ts:419:16)
    at new KeyPair (/Users/someone/code/node_modules/cdk-ec2-key-pair/lib/index.ts:271:32)
    at new CommonStack (/Users/someone/code/lib/stacks/common/index.ts:43:27)
    at App.buildBase (/Users/someone/code/lib/app.ts:41:20)
    at new App (/Users/someone/code/lib/app.ts:25:23)
    at Object.<anonymous> (/Users/someone/code/bin/cdk.ts:20:1)
```

I don't see the code.zip bundled in the npm package

![Screenshot 2024-03-25 at 9 35 30 AM](https://github.com/udondan/cdk-ec2-key-pair/assets/101210544/043154ec-5098-441d-8e8a-f40eaa53ad81)

**Comment by udondan** [comment]
Thanks @djenniex-gg! The step building the zip got lost when i switched to publib. I'll get 4.0.1 ready which should fix this.
