### ISSUE TITLE
import of module is not working

### ISSUE THREAD

**Issue by thelma1944** [udondan/cdk-ec2-key-pair#33]
import aws_cdk.aws_ec2 as ec2
Exception ignored in: <function _NodeProcess.__del__ at 0x7fcc7bd448b0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 224, in __del__
    self.stop()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 281, in stop
    if not self._process.stdin.closed:
AttributeError: '_NodeProcess' object has no attribute '_process'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/resources.py", line 173, in _path_from_reader
    yield Path(reader.resource_path(norm_resource))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_kernel/__init__.py", line 269, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 338, in load
    return self._process.send(request, LoadResponse)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_utils.py", line 24, in wrapped
    stored.append(fgetter(self))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 333, in _process
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_kernel/providers/process.py", line 250, in start
    self._process = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'node'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/aws_ec2/__init__.py", line 1443, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/aws_ec2/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.aws_cloudwatch._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/aws_cloudwatch/__init__.py", line 495, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/aws_cloudwatch/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.aws_iam._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/aws_iam/__init__.py", line 484, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/aws_iam/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.core._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/core/__init__.py", line 937, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/core/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.cloud_assembly_schema._jsii
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/cloud_assembly_schema/__init__.py", line 75, in <module>
    from ._jsii import *
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aws_cdk/cloud_assembly_schema/_jsii/__init__.py", line 11, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 166, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()

**Comment by udondan** [comment]
Just to make sure: you are familiar with CDK and other CDK modules perfectly work? 

The error message says you don't have node installed, so my first thought is, you're using this in a complete different context.

**Comment by thelma1944** [comment]
Hello Daniel,

      I will set up a 2 node system and see if this fixes the issue.
Thanks for the suggestion.

Respectfully,
Thelma Vance, PhD

**Comment by udondan** [comment]
Hi Thelma,

with node I mean NodeJS. This package is written in NodeJS and packaged for Python via [jsii](https://github.com/aws/jsii). So even if you import the Python package, you will still require node installed on the system. But this is the same for all CDK packages. So I assume you're not using CDK? Then this package will be of no use for you.

Cheers,
Daniel

**Comment by thelma1944** [comment]
Hello Daniel

    I will be using CDK soon.  I am just preparing for the development
launch.

Respectfully,
Thelma

**Comment by thelma1944** [comment]
Hello Daniel,

   I installed *NodeJS* on my MacBook Pro using an install program called
brew. Now your module works.  Thanks for the help.
   You might consider adding a line or two to indicate how to load your
module to Mac systems, just a thought.

Most respectfully and thankfully,
thelma
